library(tidyverse)

jaccard_all <- read_tsv("processed/gt_consistency/chr_all.jaccard_index.tsv")
jaccard_te <- read_tsv("processed/gt_consistency/chr_te.jaccard_index.tsv")

unique(jaccard_all$group_id)

# add 'broad' group level identifier (e.g. GTEx, Mayr) - same as used in paper
jaccard_all <- jaccard_all %>%
  mutate(group_id_simple = str_split_i(group_id, "_", 1)) %>%
  relocate(group_id_simple, .after = group_id)

jaccard_te <- jaccard_te %>%
  mutate(group_id_simple = str_split_i(group_id, "_", 1)) %>%
  relocate(group_id_simple, .after = group_id)

# transform to long format (1 row per window size for each comparison)
jaccard_all <- jaccard_all %>%
  pivot_longer(cols = starts_with("jaccardindex"),names_to = c("metric","window_size"), names_sep = "_",
               values_to = "value",
               names_transform = list(window_size = as.integer))

jaccard_te <- jaccard_te %>%
  pivot_longer(cols = starts_with("jaccardindex"),names_to = c("metric","window_size"), names_sep = "_",
               values_to = "value",
               names_transform = list(window_size = as.integer))


jaccard_comb <- bind_rows(all = jaccard_all, te = jaccard_te, .id = "pas_subset")

# remove MmusCortex because GT generated by pooling across reps
jaccard_comb <- filter(jaccard_comb, group_id_simple != "MmusCortex")

# Standard colour scale for all plots containing both all pas and subsetted for last exons
pas_subset_colour_scale <- scale_color_brewer(name = "PAS Subset",
                                                labels = c("All", "Last Exons Only"),
                                                type = "qual", palette = "Set2")

# boxplot plot using all both all and TE, aggregating into larger groups where diff tissues/conds
plot_ji_pas_subset_25nt_box <- jaccard_comb %>%
  filter(window_size == 25,
         ) %>%
  ggplot(aes(x = group_id_simple, y = value, colour = pas_subset)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(position = position_dodge2(width = 0.75), size = 0.75) +
  labs(x = "Dataset",
       y = "Jaccard Index",
       colour = "PAS Subset") +
  pas_subset_colour_scale +
  theme_bw(base_size = 14) +
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "top")

# calculate summary stats and store in df - 'dataset wide' ignoring experimental conditions 
jaccard_dataset_summ <- jaccard_comb %>%
  group_by(pas_subset, group_id_simple, window_size, metric) %>%
  summarise(median = median(value),
            iqr = IQR(value)) %>%
  ungroup()

# Some datasets have multiple 'conditions' - plot those individually
plot_ji_pas_subset_dataset_25nt_box <- jaccard_comb %>%
  filter(window_size == 0) %>%
  filter(group_id_simple %in% c("GTEXsim", "HEK293", "Mayr")) %>%
  ggplot(aes(x = group_id, y = value, colour = pas_subset)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(position = position_dodge2(width = 0.75),size = 0.75) +
  pas_subset_colour_scale +
  labs(x = "Dataset",
       y = "Jaccard Index",
       colour = "PAS Subset") +
  theme_bw(base_size = 14) +
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "top")


# Is the Mayr performance affected by window size? only assessed 0 so far
 
# jaccard_comb %>%
 #  filter(group_id_simple == "Mayr") %>%
 #  mutate(window_size = factor(window_size, levels = c(0,10,25,50))) %>%
 #  ggplot(aes( x = window_size, y = value)) +
 #  facet_wrap("~ group_id", ncol = 1) +
 #  geom_boxplot(outlier.shape = NA) +
 #  geom_jitter()

# Effect of window size on jaccard index
plot_ji_pas_subset_windows_box <-jaccard_comb %>%
  mutate(window_size = factor(window_size, levels = c(0,10,25,50))) %>%
  # filter(pas_subset == "all") %>%
  ggplot(aes( x = window_size, y = value, colour = pas_subset)) +
  facet_wrap("~ group_id_simple", ncol = 2) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(position = position_dodge2(width = 0.75), size = 0.5) +
  pas_subset_colour_scale +
  labs(x = "Window size either side of PAS (nt)",
       y = "Jaccard Index") +
  theme_bw(base_size = 14) +
  theme(legend.position = "top")

# Calculate differences in jaccard index between smallest and largest window size
jaccard_window_min_max_summ <- jaccard_comb %>%
  group_by(pas_subset, group_id_simple, window_size, metric) %>%
  summarise(median = median(value),
            iqr = IQR(value)) %>%
  group_by(pas_subset, group_id_simple) %>%
  arrange(pas_subset, group_id_simple, window_size, by_group = TRUE) %>%
  summarise(diff_0_to_50 = last(median) - first(median)) %>%
  ungroup()


plot_ji_pas_subset_25nt_box
plot_ji_pas_subset_dataset_25nt_box
plot_ji_pas_subset_windows_box

# Key points so far:
## Jaccard indices slightly higher for last-exon overlapping PAS than complete PASome
## Datasets all have median > 0.6, Mayr exhibits the greatest variability
## Calculation was performed 'within condition' for each dataset
## Mayr dataset variability is driven by a single sub-group ('Mayr_NB'). Within that sub-group, approx half comparisons are ~ 0.3, with remaining similar score to other datasets
## Increasing window size has very minor effect on jaccard index (slight increase in most cases)


#  Should do naive cluster analysis, concerned that jaccard index metric is normalised to length of interval in some way

# Save plots to disk
if (!dir.exists("processed/")) {dir.create("processed")}

# 100mm wide = ~ 1/2 A4 size, 100mm tall = ~ 1/3 A4 size


devices <- c("pdf", "png", svg) %>%
  set_names(".pdf", ".png", ".svg")

# boxplot aggregating across all ocnds in dataset with representative 25nt window size
walk2(.x = names(devices), # file suffix
      .y = devices,
      ~ ggsave(filename = paste0("2024-04-22_", "jaccard_index_dataset_wide_25nt_boxplot", .x),
               plot = plot_ji_pas_subset_25nt_box,
               path = "processed/gt_consistency/",
               device = .y,
               width = 100,
               height = 100,
               units = "mm",
               dpi = "retina")
      )

#  boxplot faceted by dataset comapring dataset-wide jaccard indices as function of window size
walk2(.x = names(devices), # file suffix
      .y = devices,
      ~ ggsave(filename = paste0("2024-04-22_", "jaccard_index_condition_wide_window_size_boxplot", .x),
               plot = plot_ji_pas_subset_windows_box,
               path = "processed/gt_consistency/",
               device = .y,
               width = 100,
               height = 100,
               units = "mm",
               dpi = "retina")
)

# boxplot of datasets split by experimental condition with rep window size
walk2(.x = names(devices), # file suffix
      .y = devices,
      ~ ggsave(filename = paste0("2024-04-22_", "jaccard_index_condition_wide_25nt_boxplot", .x),
               plot = plot_ji_pas_subset_dataset_25nt_box,
               path = "processed/gt_consistency/",
               device = .y,
               width = 100,
               height = 100,
               units = "mm",
               dpi = "retina")
)

